# Generated by Django 3.2.20 on 2023-08-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postcode',
        ),
    ]
